### ISSUE TITLE
docker build失败

### ISSUE THREAD

**Issue by zzjjbb** [nonebot/nb-cli#10]
看了一下输出，失败的原因大概是这个
```
 Command ['/usr/local/bin/python3', '-m', 'pip', 'install', '--no-deps', '/root/.cache/pypoetry/artifacts/ea/be/62/0291d882c12b3d210d26774eed82a79e44322ca990eac532e3b803ad7c/pyrsistent-0.18.0-cp38-cp38-manylinux1_x86_64.whl'] errored with the following return code 1, and output:
  Processing /root/.cache/pypoetry/artifacts/ea/be/62/0291d882c12b3d210d26774eed82a79e44322ca990eac532e3b803ad7c/pyrsistent-0.18.0-cp38-cp38-manylinux1_x86_64.whl
  Installing collected packages: pyrsistent
  Successfully installed pyrsistent-0.18.0
  Traceback (most recent call last):
    File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "/usr/local/lib/python3.8/site-packages/pip/__main__.py", line 26, in <module>
      sys.exit(_main())
    File "/usr/local/lib/python3.8/site-packages/pip/_internal/cli/main.py", line 75, in main
      return command.main(cmd_args)
    File "/usr/local/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 117, in main
      return self._main(args)
    File "/usr/local/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 261, in _main
      self.handle_pip_version_check(options)
    File "/usr/local/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 147, in handle_pip_version_check
      session = self._build_session(
    File "/usr/local/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 88, in _build_session
      session = PipSession(
    File "/usr/local/lib/python3.8/site-packages/pip/_internal/network/session.py", line 248, in __init__
      self.headers["User-Agent"] = user_agent()
    File "/usr/local/lib/python3.8/site-packages/pip/_internal/network/session.py", line 158, in user_agent
      setuptools_version = get_installed_version("setuptools")
    File "/usr/local/lib/python3.8/site-packages/pip/_internal/utils/misc.py", line 668, in get_installed_version
      working_set = pkg_resources.WorkingSet()
    File "/usr/local/lib/python3.8/site-packag Command ['/usr/local/bin/python3', '-m', 'pip', 'install', '--no-deps', '/root/.cache/pypoetry/artifacts/ea/be/62/0291d882c12b3d210d26774eed82a79e44322ca990eac532e3b803ad7c/pyrsistent-0.18.0-cp38-cp38-manylinux1_x86_64.whl'] errored with the following return code 1, and output:
  Processing /root/.cache/pypoetry/artifacts/ea/be/62/0291d882c12b3d210d26774eed82a79e44322ca990eac532e3b803ad7c/pyrsistent-0.18.0-cp38-cp38-manylinux1_x86_64.whl
  Installing collected packages: pyrsistent
  Successfully installed pyrsistent-0.18.0
  Traceback (most recent call last):
    File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "/usr/local/lib/python3.8/site-packages/pip/__main__.py", line 26, in <module>
      sys.exit(_main())
    File "/usr/local/lib/python3.8/site-packages/pip/_internal/cli/main.py", line 75, in main
      return command.main(cmd_args)
    File "/usr/local/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 117, in main
      return self._main(args)
    File "/usr/local/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 261, in _main
      self.handle_pip_version_check(options)
    File "/usr/local/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 147, in handle_pip_version_check
      session = self._build_session(
    File "/usr/local/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 88, in _build_session
      session = PipSession(
    File "/usr/local/lib/python3.8/site-packages/pip/_internal/network/session.py", line 248, in __init__
      self.headers["User-Agent"] = user_agent()
    File "/usr/local/lib/python3.8/site-packages/pip/_internal/network/session.py", line 158, in user_agent
      setuptools_version = get_installed_version("setuptools")
    File "/usr/local/lib/python3.8/site-packages/pip/_internal/utils/misc.py", line 668, in get_installed_version
      working_set = pkg_resources.WorkingSet()
    File "/usr/local/lib/python3.8/site-packages/pip/_vendor/pkg_resources/__init__.py", line 567, in __init__
      self.add_entry(entry)
    File "/usr/local/lib/python3.8/site-packages/pip/_vendor/pkg_resources/__init__.py", line 623, in add_entry
      for dist in find_distributions(entry, True):
    File "/usr/local/lib/python3.8/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2065, in find_on_path
      for dist in factory(fullpath):
    File "/usr/local/lib/python3.8/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2127, in distributions_from_metadata
      if len(os.listdir(path)) == 0:
  FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.8/site-packages/~ython_dotenv-0.15.0.dist-info'
es/pip/_vendor/pkg_resources/__init__.py", line 567, in __init__
      self.add_entry(entry)
    File "/usr/local/lib/python3.8/site-packages/pip/_vendor/pkg_resources/__init__.py", line 623, in add_entry
      for dist in find_distributions(entry, True):
    File "/usr/local/lib/python3.8/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2065, in find_on_path
      for dist in factory(fullpath):
    File "/usr/local/lib/python3.8/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2127, in distributions_from_metadata
      if len(os.listdir(path)) == 0:
  FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.8/site-packages/~ython_dotenv-0.15.0.dist-info'
```

**Comment by zzjjbb** [comment]
是其他依赖包本身有问题吗？

**Comment by zzjjbb** [comment]
重试之后没有复现，可能是我网络问题？

**Comment by yanyongyu** [comment]
并不能看出什么问题，尝试一下重新安装吧，如果还不行就别用poetry安装
