### ISSUE TITLE
nb plugin list 报错

### ISSUE THREAD

**Issue by zhuting233** [nonebot/nb-cli#29]
版本
nb-cli                 0.6.4
nonebot-adapter-onebot 2.0.0b1
nonebot2               2.0.0b1

报错如下
```python
# D:\code\nb\bot>nb plugin list
Traceback (most recent call last):
  File "C:\Users\zhuqi\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\zhuqi\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\zhuqi\AppData\Local\Programs\Python\Python310\Scripts\nb.exe\__main__.py", line 7, in <module>
  File "C:\Users\zhuqi\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\zhuqi\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\Users\zhuqi\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\zhuqi\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\zhuqi\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\zhuqi\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\zhuqi\AppData\Local\Programs\Python\Python310\lib\site-packages\nb_cli\commands\plugin.py", line 25, in list
    search_plugin("")
  File "C:\Users\zhuqi\AppData\Local\Programs\Python\Python310\lib\site-packages\nb_cli\handlers\plugin.py", line 136, in search_plugin
    print_package_results(plugins)
  File "C:\Users\zhuqi\AppData\Local\Programs\Python\Python310\lib\site-packages\nb_cli\utils.py", line 133, in print_package_results
    [
  File "C:\Users\zhuqi\AppData\Local\Programs\Python\Python310\lib\site-packages\nb_cli\utils.py", line 134, in <listcomp>
    len(f"{hit.name} ({hit.project_link})".encode("gbk"))
UnicodeEncodeError: 'gbk' codec can't encode character '\U0001f637' in position 6: illegal multibyte sequence
```

**Comment by j1g5awi** [comment]
Relative #2

**Comment by yanyongyu** [comment]
fix in nonebot/nonebot2#702
