### ISSUE TITLE
Feature: 建议禁止用户设置特定的项目名称

### ISSUE THREAD

**Issue by OREOCODEDEV** [nonebot/nb-cli#47]
当用户以类似`bot`、`nonebot`等作为项目名称时，会造成 NoneBot2 意料之外的错误，且难以诊断错误原因
如下是名称为`bot`的项目尝试加载本地插件时所遇到的错误
```
12-30 01:59:39 [ERROR] nonebot | Failed to import "nonebot_plugin_calculator"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\users\oreo\appdata\local\programs\python\python39\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "c:\users\oreo\appdata\local\programs\python\python39\lib\multiprocessing\spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "c:\users\oreo\appdata\local\programs\python\python39\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "c:\users\oreo\appdata\local\programs\python\python39\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\oreo\appdata\local\programs\python\python39\lib\site-packages\uvicorn\_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "c:\users\oreo\appdata\local\programs\python\python39\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "c:\users\oreo\appdata\local\programs\python\python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "c:\users\oreo\appdata\local\programs\python\python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "c:\users\oreo\appdata\local\programs\python\python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "c:\users\oreo\appdata\local\programs\python\python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "c:\users\oreo\appdata\local\programs\python\python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "c:\users\oreo\appdata\local\programs\python\python39\lib\site-packages\uvicorn\server.py", line 67, in serve
    config.load()
  File "c:\users\oreo\appdata\local\programs\python\python39\lib\site-packages\uvicorn\config.py", line 477, in load
    self.loaded_app = import_from_string(self.app)
  File "c:\users\oreo\appdata\local\programs\python\python39\lib\site-packages\uvicorn\importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "c:\users\oreo\appdata\local\programs\python\python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "D:\Users\OREO\Documents\pytest\bot\.\bot.py", line 27, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "c:\users\oreo\appdata\local\programs\python\python39\lib\site-packages\nonebot\plugin\load.py", line 122, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "c:\users\oreo\appdata\local\programs\python\python39\lib\site-packages\nonebot\plugin\load.py", line 59, in load_all_plugins
    return manager.load_all_plugins()
  File "c:\users\oreo\appdata\local\programs\python\python39\lib\site-packages\nonebot\plugin\manager.py", line 168, in load_all_plugins
    return set(
  File "c:\users\oreo\appdata\local\programs\python\python39\lib\site-packages\nonebot\plugin\manager.py", line 169, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "c:\users\oreo\appdata\local\programs\python\python39\lib\site-packages\nonebot\plugin\manager.py", line 145, in load_plugin
    module = importlib.import_module(
  File "c:\users\oreo\appdata\local\programs\python\python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 981, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'bot.plugins'; 'bot' is not a package
```
建议通过禁止用户设置特定的项目名称以避免类似问题

**Comment by yanyongyu** [comment]
nonebot这个名称应该禁止 bot 这个名称在没有bot.py之后就不受影响了

**Comment by StarHeartHunt** [comment]
补充：Python builtin 库所使用的名字同样不应该被作为项目名

**Comment by yanyongyu** [comment]
这个blacklist应该怎么生成呢
