### ISSUE TITLE
[bug?]`nb run`报错`NoneBotNotInstalledError`，但是nonebot2已安装

### ISSUE THREAD

**Issue by shoucandanghehe** [nonebot/nb-cli#60]
```
code\Developing\ababbot is 📦 v0.1.0 via 🐍 v3.11.1 (ababbot-py3.11) 
❯ nb
d8b   db  .d88b.  d8b   db d88888b d8888b.  .d88b.  d888888b
888o  88 .8P  Y8. 888o  88 88'     88  `8D .8P  Y8. `~~88~~'
88V8o 88 88    88 88V8o 88 88ooooo 88oooY' 88    88    88
88 V8o88 88    88 88 V8o88 88~~~~~ 88~~~b. 88    88    88
88  V888 `8b  d8' 88  V888 88.     88   8D `8b  d8'    88
VP   V8P  `Y88P'  VP   V8P Y88888P Y8888P'  `Y88P'     YP


欢迎使用 NoneBot CLI!
[?] 你想要进行什么操作? 管理 NB CLI.
[?] 你想要进行什么操作? 列出 cli 虚拟环境中已安装的包.
Package                Version
---------------------- ---------
aiohttp                3.8.3
aiosignal              1.3.1
aiosqlite              0.17.0
anyio                  3.6.2
arrow                  1.2.3
async-timeout          4.0.2
asyncio                3.4.3
attrs                  22.2.0
binaryornot            0.4.4
black                  23.1a1
cashews                5.0.0
certifi                2022.12.7
chardet                5.1.0
charset-normalizer     2.1.1
click                  8.1.3
colorama               0.4.6
cookiecutter           2.1.1
distlib                0.3.6
fastapi                0.89.1
filelock               3.9.0
frozenlist             1.3.3
greenlet               2.0.1
h11                    0.14.0
httpcore               0.16.3
httptools              0.5.0
httpx                  0.23.3
idna                   3.4
iso8601                1.1.0
Jinja2                 3.1.2
jinja2-time            0.2.0
loguru                 0.6.0
lxml                   4.9.2
MarkupSafe             2.1.2
msgpack                1.0.4
multidict              6.0.4
mypy-extensions        0.4.3
nb-cli                 1.0.3
nonebot-adapter-onebot 2.2.1
nonebot2               2.0.0rc3
noneprompt             0.1.7
numpy                  1.24.1
pandas                 1.5.3
pathspec               0.11.0
pip                    22.3.1
platformdirs           2.6.2
playwright             1.30.0
prompt-toolkit         3.0.36
pydantic               1.10.4
pyee                   9.0.4
pyfiglet               0.8.post1
pygtrie                2.5.0
pypika-tortoise        0.1.6
python-dateutil        2.8.2
python-dotenv          0.21.1
python-slugify         8.0.0
pytz                   2022.7.1
PyYAML                 6.0
requests               2.28.2
rfc3986                1.5.0
ruff                   0.0.193
setuptools             65.6.3
six                    1.16.0
sniffio                1.3.0
starlette              0.22.0
text-unidecode         1.3
tomlkit                0.11.6
tortoise-orm           0.19.3
typing_extensions      4.4.0
ujson                  5.7.0
urllib3                1.26.14
uvicorn                0.20.0
virtualenv             20.17.1
watchfiles             0.18.1
wcwidth                0.2.6
websockets             10.4
wheel                  0.38.4
win32-setctime         1.1.0
yarl                   1.8.2

[notice] A new release of pip available: 22.3.1 -> 23.0
[notice] To update, run: python.exe -m pip install --upgrade pip

code\Developing\ababbot is 📦 v0.1.0 via 🐍 v3.11.1 (ababbot-py3.11) took 8s
❯ nb run
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\17486\AppData\Local\pypoetry\Cache\virtualenvs\ababbot-iMOxTe1J-py3.11\Scripts\nb.exe\__main__.py", line 7, in <module>
  File "C:\Users\17486\AppData\Local\pypoetry\Cache\virtualenvs\ababbot-iMOxTe1J-py3.11\Lib\site-packages\nb_cli\__main__.py", line 7, in main
    anyio.run(cli_main, *args)
  File "C:\Users\17486\AppData\Local\pypoetry\Cache\virtualenvs\ababbot-iMOxTe1J-py3.11\Lib\site-packages\anyio\_core\_eventloop.py", line 70, in run
    return asynclib.run(func, *args, **backend_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\17486\AppData\Local\pypoetry\Cache\virtualenvs\ababbot-iMOxTe1J-py3.11\Lib\site-packages\anyio\_backends\_asyncio.py", line 292, in run
    return native_run(wrapper(), debug=debug)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\17486\AppData\Local\pypoetry\Cache\virtualenvs\ababbot-iMOxTe1J-py3.11\Lib\site-packages\anyio\_backends\_asyncio.py", line 287, in wrapper
    return await func(*args)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\17486\AppData\Local\pypoetry\Cache\virtualenvs\ababbot-iMOxTe1J-py3.11\Lib\site-packages\nb_cli\__init__.py", line 35, in cli_main
    return await run_sync(cli_sync)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\17486\AppData\Local\pypoetry\Cache\virtualenvs\ababbot-iMOxTe1J-py3.11\Lib\site-packages\nb_cli\cli\utils.py", line 61, in wrapper
    return await anyio.to_thread.run_sync(partial(func, *args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\17486\AppData\Local\pypoetry\Cache\virtualenvs\ababbot-iMOxTe1J-py3.11\Lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\17486\AppData\Local\pypoetry\Cache\virtualenvs\ababbot-iMOxTe1J-py3.11\Lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread       
    return await future
           ^^^^^^^^^^^^
  File "C:\Users\17486\AppData\Local\pypoetry\Cache\virtualenvs\ababbot-iMOxTe1J-py3.11\Lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\17486\AppData\Local\pypoetry\Cache\virtualenvs\ababbot-iMOxTe1J-py3.11\Lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\17486\AppData\Local\pypoetry\Cache\virtualenvs\ababbot-iMOxTe1J-py3.11\Lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\17486\AppData\Local\pypoetry\Cache\virtualenvs\ababbot-iMOxTe1J-py3.11\Lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\17486\AppData\Local\pypoetry\Cache\virtualenvs\ababbot-iMOxTe1J-py3.11\Lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\17486\AppData\Local\pypoetry\Cache\virtualenvs\ababbot-iMOxTe1J-py3.11\Lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\17486\AppData\Local\pypoetry\Cache\virtualenvs\ababbot-iMOxTe1J-py3.11\Lib\site-packages\nb_cli\cli\utils.py", line 69, in wrapper
    return anyio.from_thread.run(partial(func, *args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\17486\AppData\Local\pypoetry\Cache\virtualenvs\ababbot-iMOxTe1J-py3.11\Lib\site-packages\anyio\from_thread.py", line 49, in run
    return asynclib.run_async_from_thread(func, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\17486\AppData\Local\pypoetry\Cache\virtualenvs\ababbot-iMOxTe1J-py3.11\Lib\site-packages\anyio\_backends\_asyncio.py", line 970, in run_async_from_thread
    return f.result()
           ^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\17486\AppData\Local\pypoetry\Cache\virtualenvs\ababbot-iMOxTe1J-py3.11\Lib\site-packages\nb_cli\cli\commands\project.py", line 360, in run
    proc = await run_project(
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\17486\AppData\Local\pypoetry\Cache\virtualenvs\ababbot-iMOxTe1J-py3.11\Lib\site-packages\nb_cli\handlers\meta.py", line 113, in wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\17486\AppData\Local\pypoetry\Cache\virtualenvs\ababbot-iMOxTe1J-py3.11\Lib\site-packages\nb_cli\handlers\meta.py", line 158, in wrapper
    raise NoneBotNotInstalledError(_("NoneBot is not installed."))
nb_cli.exceptions.NoneBotNotInstalledError: NoneBot 未安装.

```

**Comment by shoucandanghehe** [comment]
pyproject.toml 依赖声明
```
[tool.poetry.dependencies]
python = "^3.10,<3.12"
nonebot2 = {extras = ["fastapi"], version = "^2.0.0rc3"}
nonebot-adapter-onebot = "^2.0.0-beta.1"
aiohttp = "^3.8.1"
asyncio = "^3.4.3"
lxml = "^4.9.1"
pandas = "^1.4.3"
playwright = "^1.24.1"
ujson = "^5.4.0"
tortoise-orm = "^0.19.2"

[tool.poetry.group.dev.dependencies]
ruff = "^0.0.193"
black = {version = "^23.1a1", allow-prereleases = true}
nb-cli = "^1.0.3"
```

**Comment by yanyongyu** [comment]
请不要在nbcli的虚拟环境中安装nonebot2

**Comment by shoucandanghehe** [comment]
> 请确认你的环境中`python3`正确指向你nonebot安装的环境
大概找到问题了
```
code\Developing\ababbot is 📦 v0.1.0 via 🐍 v3.11.1 (ababbot-py3.11) took 7s
❯ gcm python

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     python.exe                                         3.11.1150… C:\Users\17486\AppData\Local\pypoetry\Cache\virtualenvs\ababbot-iMOxTe1J-py3.11/Scripts\python.exe     


code\Developing\ababbot is 📦 v0.1.0 via 🐍 v3.11.1 (ababbot-py3.11) 
❯ gcm python3

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     python3.exe                                        0.0.0.0    C:\Users\17486\scoop\shims\python3.exe
```

**Comment by yanyongyu** [comment]
venv默认会创建python3软链接

**Comment by shoucandanghehe** [comment]
> venv默认会创建python3软链接，nbcli优先使用python3，如果找不到会用python

我用的几个管理器似乎都没创建链接（
[virtualenvwrapper-powershell](https://github.com/regisf/virtualenvwrapper-powershell) [poetry](https://github.com/python-poetry/poetry) [miniconda](https://docs.conda.io/en/latest/miniconda.html)
我再去研究一下，这个issue先关掉了

**Comment by yanyongyu** [comment]
poetry miniconda 都会创建。。。

**Comment by shoucandanghehe** [comment]
~~但是我是Windows~~

**Comment by yanyongyu** [comment]
另外你可以让poetry venv in-project，这样nbcli可以自动识别

**Comment by shoucandanghehe** [comment]
> Linux上poetry miniconda 都会创建。。。

或许是因为Linux上的python3就叫python3
创建的别名应该是python（？
~~sudo apt install python-is-python3~~

**Comment by yanyongyu** [comment]
![image](https://user-images.githubusercontent.com/42488585/215725510-912cfb49-4dc7-4f6a-895e-2231a49e7614.png)
