### ISSUE TITLE
nb时找不到可用的解释器

### ISSUE THREAD

**Issue by OverSky-gtq** [nonebot/nb-cli#76]
```python
Traceback (most recent call last):
  File "C:\Users\guo\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\guo\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\users\guo\.local\bin\nb.exe\__main__.py", line 7, in <module>
  File "C:\Users\guo\.local\pipx\venvs\nb-cli\lib\site-packages\nb_cli\__main__.py", line 10, in main
    anyio.run(cli_main, *args)
  File "C:\Users\guo\.local\pipx\venvs\nb-cli\lib\site-packages\anyio\_core\_eventloop.py", line 70, in run
    return asynclib.run(func, *args, **backend_options)
  File "C:\Users\guo\.local\pipx\venvs\nb-cli\lib\site-packages\anyio\_backends\_asyncio.py", line 292, in run
    return native_run(wrapper(), debug=debug)
  File "C:\Users\guo\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\guo\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\guo\.local\pipx\venvs\nb-cli\lib\site-packages\anyio\_backends\_asyncio.py", line 287, in wrapper
    return await func(*args)
  File "C:\Users\guo\.local\pipx\venvs\nb-cli\lib\site-packages\nb_cli\__init__.py", line 35, in cli_main
    return await run_sync(cli_sync)(*args, **kwargs)
  File "C:\Users\guo\.local\pipx\venvs\nb-cli\lib\site-packages\nb_cli\cli\utils.py", line 61, in wrapper
    return await anyio.to_thread.run_sync(partial(func, *args, **kwargs))
  File "C:\Users\guo\.local\pipx\venvs\nb-cli\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\guo\.local\pipx\venvs\nb-cli\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\guo\.local\pipx\venvs\nb-cli\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\guo\.local\pipx\venvs\nb-cli\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\guo\.local\pipx\venvs\nb-cli\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\guo\.local\pipx\venvs\nb-cli\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\guo\.local\pipx\venvs\nb-cli\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\guo\.local\pipx\venvs\nb-cli\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\guo\.local\pipx\venvs\nb-cli\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\guo\.local\pipx\venvs\nb-cli\lib\site-packages\nb_cli\cli\utils.py", line 69, in wrapper
    return anyio.from_thread.run(partial(func, *args, **kwargs))
  File "C:\Users\guo\.local\pipx\venvs\nb-cli\lib\site-packages\anyio\from_thread.py", line 49, in run
    return asynclib.run_async_from_thread(func, *args)
  File "C:\Users\guo\.local\pipx\venvs\nb-cli\lib\site-packages\anyio\_backends\_asyncio.py", line 970, in run_async_from_thread
    return f.result()
  File "C:\Users\guo\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 458, in result
    return self.__get_result()
  File "C:\Users\guo\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "C:\Users\guo\.local\pipx\venvs\nb-cli\lib\site-packages\nb_cli\cli\commands\project.py", line 222, in create
    await create_virtualenv(
  File "C:\Users\guo\.local\pipx\venvs\nb-cli\lib\site-packages\nb_cli\handlers\meta.py", line 114, in wrapper
    version = await get_python_version(
  File "C:\Users\guo\.local\pipx\venvs\nb-cli\lib\site-packages\cashews\wrapper\decorators.py", line 46, in _call
    return await decorator(*args, **kwargs)
  File "C:\Users\guo\.local\pipx\venvs\nb-cli\lib\site-packages\cashews\decorators\cache\simple.py", line 54, in _wrap
    result = await func(*args, **kwargs)
  File "C:\Users\guo\.local\pipx\venvs\nb-cli\lib\site-packages\nb_cli\handlers\meta.py", line 94, in get_python_version
    python_path = await get_default_python()
  File "C:\Users\guo\.local\pipx\venvs\nb-cli\lib\site-packages\cashews\wrapper\decorators.py", line 46, in _call
    return await decorator(*args, **kwargs)
  File "C:\Users\guo\.local\pipx\venvs\nb-cli\lib\site-packages\cashews\decorators\cache\simple.py", line 54, in _wrap
    result = await func(*args, **kwargs)
  File "C:\Users\guo\.local\pipx\venvs\nb-cli\lib\site-packages\nb_cli\handlers\meta.py", line 81, in get_default_python
    raise PythonInterpreterError(_("Cannot find a valid Python interpreter."))
nb_cli.exceptions.PythonInterpreterError: 无法找到可用的 Python 解释器.
```

**Comment by yanyongyu** [comment]
请确认python是否在环境变量PATH里，是否可以在shell中直接使用python命令

**Comment by OverSky-gtq** [comment]
已解决。原因是环境变量里一个无效的python文件的优先级更高，调整顺序后解决了
