### ISSUE TITLE
Bug: `os.PathLike` is not Generic

### ISSUE THREAD

**Issue by dzx-dzx** [nonebot/nb-cli#77]
Python3.8.10，创建虚拟环境并按照https://v2.nonebot.dev/docs/quick-start 安装脚手架后，运行`nb`提示:
```
Traceback (most recent call last):
  File "/home/***/.local/bin/nb", line 5, in <module>
    from nb_cli.__main__ import main
  File "/home/***/.local/pipx/venvs/nb-cli/lib/python3.8/site-packages/nb_cli/__init__.py", line 20, in <module>
    from .cli import run_sync
  File "/home/***/.local/pipx/venvs/nb-cli/lib/python3.8/site-packages/nb_cli/cli/__init__.py", line 8, in <module>
    from nb_cli.handlers import draw_logo
  File "/home/***/.local/pipx/venvs/nb-cli/lib/python3.8/site-packages/nb_cli/handlers/__init__.py", line 18, in <module>
    from .meta import draw_logo as draw_logo
  File "/home/***/.local/pipx/venvs/nb-cli/lib/python3.8/site-packages/nb_cli/handlers/meta.py", line 28, in <module>
    from .process import create_process, create_process_shell
  File "/home/***/.local/pipx/venvs/nb-cli/lib/python3.8/site-packages/nb_cli/handlers/process.py", line 58, in <module>
    *args: Union[str, bytes, os.PathLike[str], os.PathLike[bytes]],
TypeError: 'ABCMeta' object is not subscriptable
```
https://github.com/nonebot/nonebot/issues/200 似乎问题类似，但我已经运行过`pip install --upgrade multidict`。

**Comment by yanyongyu** [comment]
这问题。。。得升级你的python。。3.8不支持应该。得修下

**Comment by dzx-dzx** [comment]
嘶果然……那官网文档恐怕也要麻烦了。

**Comment by yanyongyu** [comment]
nbcli这边修一下就行了，这是Python版本问题
