### ISSUE TITLE
python3.8.10 无法使用nb-cli

### ISSUE THREAD

**Issue by Haocen2004** [nonebot/nb-cli#78]
```
haocen@hkVM1:~/nonebot$ nb --help
Traceback (most recent call last):
  File "/home/haocen/.local/bin/nb", line 5, in <module>
    from nb_cli.__main__ import main
  File "/home/haocen/.local/pipx/venvs/nb-cli/lib/python3.8/site-packages/nb_cli/__init__.py", line 20, in <module>
    from .cli import run_sync
  File "/home/haocen/.local/pipx/venvs/nb-cli/lib/python3.8/site-packages/nb_cli/cli/__init__.py", line 8, in <module>
    from nb_cli.handlers import draw_logo
  File "/home/haocen/.local/pipx/venvs/nb-cli/lib/python3.8/site-packages/nb_cli/handlers/__init__.py", line 18, in <module>
    from .meta import draw_logo as draw_logo
  File "/home/haocen/.local/pipx/venvs/nb-cli/lib/python3.8/site-packages/nb_cli/handlers/meta.py", line 28, in <module>
    from .process import create_process, create_process_shell
  File "/home/haocen/.local/pipx/venvs/nb-cli/lib/python3.8/site-packages/nb_cli/handlers/process.py", line 58, in <module>
    *args: Union[str, bytes, os.PathLike[str], os.PathLike[bytes]],
TypeError: 'ABCMeta' object is not subscriptable
```

```
haocen@hkVM1:~/nonebot$ python --version
Python 3.8.10
```

**Comment by yanyongyu** [comment]
Duplicate of #77

**Comment by Haocen2004** [comment]
ok 但是为什么gh搜索历史issue没出来（
